version: '3'

services:
  db:
    image: postgres
    build:
      context: ./postgres_dockerfile
      dockerfile: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  reg_redis:
    image: 'redis'
    ports:
      - "6373:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  rabbit:
    image: rabbitmq:3.6.6-management
    hostname: rabbit
    ports:
      - "5672:5672"

  goods:
    build: ./goods
    command: bash -c "python3 ./goods/manage.py makemigrations api && python ./goods/manage.py migrate && python ./goods/manage.py loaddata ./goods/fixtures/initial_data.json && python ./goods/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db

  user_service:
    build: ./user_service
    env_file:
      - user_service/.env
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      WAIT_HOSTS: db:5432, rabbit:5672
      WAIT_HOSTS_TIMEOUT: 120

  email:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.yandex.ru
      RELAY_PORT: 587
      RELAY_USERNAME: scumethy@le-memese.com
      RELAY_PASSWORD: pfQsSs9iNM3UCAAT43MN82qxgJtuDtHjuevEr5et

  mail_service:
    build: ./mail_service
    volumes:
      - .:/code
    ports:
      - "8008:8008"
    depends_on:
      - db
      - rabbit
    environment:
      WAIT_HOSTS: db:5432, rabbit:5672
      WAIT_HOSTS_TIMEOUT: 120

  monitor_service:
    build: ./monitoring_service
    volumes:
      - .:/code
    ports:
      - "8088:8088"
    depends_on:
      - db
      - rabbit
    environment:
      WAIT_HOSTS: db:5432, rabbit:5672
      WAIT_HOSTS_TIMEOUT: 120

  monitor_worker:
    build:
      context: ./monitoring_service
      dockerfile: celery-worker.Dockerfile
    volumes:
      - .:/code
    depends_on:
      - rabbit
      - monitor_service
    environment:
      WAIT_HOSTS: rabbit:5672, monitor_service:8088
      WAIT_HOSTS_TIMEOUT: 120

  general_service:
    build: ./general_service
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - goods
      - user_service
      - mail_service
      - monitor_service
    environment:
      WAIT_HOSTS: db:5432, reg_redis:6379, goods:8001, user_service:8080, mail_service:8008, monitor_service:8088
      WAIT_HOSTS_TIMEOUT: 120

volumes:
  monitor_service: